name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: test
        run: make test
