name: CI

on:
  workflow_run:
    workflows: ["Format"]
    types:
      - completed

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: test
        run: make test
