name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ !cancelled() }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: setup formatters
        run: |
          sudo ./ci/setup_clang.sh
          sudo ./ci/setup_python.sh
      - name: format C/C++ sources
        run: ./ci/run_clang_format.sh
      - name: format python sources
        run: ./ci/run_black_format.sh
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "format: Apply formatting changes"
          branch: ${{ github.head_ref }}
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ !cancelled() }}
    needs: [ format ]

    steps:
      - uses: actions/checkout@v3
      - name: test
        run: make test
